---
version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: debezium/kafka:1.1
    container_name: kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
    # Exposes 9092 for external connections to the broker
    # Use kafka:29092 for connections internal on the docker network
      - 9092:9092
    environment:
      - BROKER_ID=1
      - ADVERTISED_HOST_NAME=192.168.0.14
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - ADVERTISED_LISTENERS=PLAINTEXT://192.168.0.14:9092

  mysql:
    # *-----------------------------*
    # To connect to the DB:
    #   docker exec -it mysql bash -c 'mysql -u root -p$MYSQL_ROOT_PASSWORD'
    # or
    #   docker exec -it mysql bash -c 'mysql -u $MYSQL_USER -p$MYSQL_PASSWORD demo'
    # *-----------------------------*
    image: debezium/example-mysql:1.1
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"

  connect-1:
    image: debezium/connect:1.1
    hostname: connect-1
    container_name: connect-1
    ports:
      - 8083:8083
    links:
      - zookeeper
      - kafka
      - mysql
      - elasticsearch
    environment:
      - GROUP_ID=1
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  connect-2:
    image: debezium/connect:1.1
    hostname: connect-2
    container_name: connect-2
    ports:
      - 8084:8083
    volumes:
      - ./connectors/confluentinc-kafka-connect-elasticsearch-5.3.1/lib:/kafka/connect/elasticsearch/
    links:
      - zookeeper
      - kafka
      - mysql
      - elasticsearch
    environment:
      - GROUP_ID=1
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses