---
version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: debezium/kafka
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
    # Exposes 9092 for external connections to the broker
    # Use kafka:29092 for connections internal on the docker network
      - 9092:9092
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  mysql:
    # *-----------------------------*
    # To connect to the DB:
    #   docker exec -it mysql bash -c 'mysql -u root -p$MYSQL_ROOT_PASSWORD'
    # or
    #   docker exec -it mysql bash -c 'mysql -u $MYSQL_USER -p$MYSQL_PASSWORD demo'
    # *-----------------------------*
    image: debezium/example-mysql
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
#    volumes:
#      - //C:/workspace/amaiza/kafka-connect/docker/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"
      node.store.allow_mmap: "false"

  connect-1:
    image: debezium/connect:1.0
    hostname: connect-1
    container_name: connect-1
    ports:
      - 8084:8083
    links:
      - zookeeper
      - kafka
      - mysql
      - elasticsearch
    environment:
      - GROUP_ID=1
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  connect-2:
    image: debezium/connect:1.0
    hostname: connect-2
    container_name: connect-2
    ports:
      - 8083:8083
    links:
      - zookeeper
      - kafka
      - mysql
      - elasticsearch
    environment:
      - GROUP_ID=1
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

